### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by showduhtung** [ajhenry/react-google-slides#15]
Will this work when you're not logged into the link's google account?

**Comment by AJHenry** [comment]
That's up the slide deck's sharing settings. For example, the slides need to be published in order to be accessed publically

[Here's a google help link](https://support.google.com/docs/answer/183965?hl=en&co=GENIE.Platform=Desktop) for making slides public

Its also possible that if you are behind a corporate proxy that items from external google accounts are blocked by default

**Comment by showduhtung** [comment]
Thanks for the response!
